# Generated by Django 5.2.6 on 2025-09-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Tareffa_Flow", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tareffa_Flow",
            new_name="Tarefa",
        ),
    ]
