# Generated by Django 5.2.6 on 2025-09-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tareffa_Flow", "0002_rename_tareffa_flow_tarefa"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="concluida",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
