# Generated by Django 5.2.6 on 2025-09-29 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tareffa_Flow", "0003_tarefa_concluida_tarefa_descricao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="criador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarefas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
