# Generated by Django 5.2.6 on 2025-09-29 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tareffa_Flow", "0008_alter_tarefa_criador"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarefa",
            options={"ordering": ["-deadline"]},
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Título"),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarefa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="Tareffa_Flow.tarefa",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
